web:
  build: .
  command: bundle exec ruby app.rb
  ports:
    - 8084:4567
  volumes:
    - .:/app
  links:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
redis:
  image: registry.default.kube.cluster.local/redis
